apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-deployment
  labels:
    app: browser
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
        - name: browser
          image: klausmeyer/docker-registry-browser:1.3.1
          ports:
            - containerPort: 8080
          command:
            - sh
            - -cex
            - |
              DOCKER_REGISTRY_URL=http://$${DOCKER_REGISTRY_URL} puma -C config/puma.rb
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "50m"
          env:
            - name: ENABLE_DELETE_IMAGES
              value: "true"
            - name: DOCKER_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: network-ip-assignments
                  key: registry
---
apiVersion: v1
kind: Service
metadata:
  name: browser
  labels:
    app: browser
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: browser
