apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-deployment
  labels:
    app: browser
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: browser
          image: registry.internal.aleemhaji.com/browser:1.3.5
          ports:
            - containerPort: 8080
          env:
            - name: ENABLE_DELETE_IMAGES
              value: "true"
            - name: DOCKER_REGISTRY_URL
              value: https://registry.internal.aleemhaji.com
---
apiVersion: v1
kind: Service
metadata:
  name: browser
  labels:
    app: browser
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: browser
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: browser-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://browser.internal.aleemhaji.com
spec:
  rules:
    - host: browser
    - host: browser.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: browser-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - browser.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: browser.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: browser
              servicePort: 8080
