apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    app: registry
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: registry-persistent-storage
              mountPath: /var/lib/registry
            - name: htpasswd-secrets
              mountPath: /auth
          env:
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:80
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "registry.internal.aleemhaji.com"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
      volumes:
        - name: registry-persistent-storage
          nfs:
            server: 192.168.96.4
            path: /mnt/main/apps/docker-registry
        - name: htpasswd-secrets
          projected:
            sources:
              - secret:
                  name: registry.internal.aleemhaji.com-htpasswd
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
    - port: 80
      protocol: TCP
  type: NodePort
  selector:
    app: registry
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://registry.internal.aleemhaji.com
spec:
  rules:
    - host: registry
    - host: registry.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - registry.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: registry.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: registry
              servicePort: 80
