apiVersion: v1
data:
    .dockerconfigjson: ${DOCKER_CONFIG_JSON_FILE_CONTENTS_BASE64}
kind: Secret
metadata:
    name: ${DOCKER_REGISTRY_HOSTNAME}
    namespace: ${NAMESPACE}
type: kubernetes.io/dockerconfigjson
