apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-manager
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-manager
subjects:
  - kind: ServiceAccount
    name: dns-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: dns-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-manager-deployment
  labels:
    app: dns-manager
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: dns-manager
  template:
    metadata:
      labels:
        app: dns-manager
    spec:
      serviceAccountName: dns-manager
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: dns-manager
          image: registry.internal.aleemhaji.com/nsdns:v0.1.3
          command:
            - nsdns
            - watch
            - --domain
            - aleemhaji.com
            - --ingress-class
            - nginx-external
          env:
            - name: NAMESILO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: namesilo-api-key
                  key: value
