# When the docker process is running on a virtual machine of some kind, there
#   are some kinds of applications that don't tend to run very well.
# Anything hosting any kind of a database tends to behave pretty poorly, 
#   including SQLite databases. Anything that doesn't connect to another
#   service to store its data will use a named docker volume for its storage.
# This also assumes that the VM that docker is running in has bound to port 22
#   for its own management.
version: '3'
services:
  sharelatex:
    volumes:
      - 'sharelatex-data:/var/lib/sharelatex'
  mongodb:
    volumes:
      - 'mongodb-data:/db/data'
  mysql:
    volumes:
      - 'mysql-data:/var/lib/data'
  util:
    ports:
      - '2000:22'
  plex:
    volumes:
      - 'plex-config:/config'

volumes:
  sharelatex-data:
    external: true
  mongodb-data:
    external: true
  mysql-data:
    external: true
  plex-config:
    external: true
