apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s-pod-scraping
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s-pod-scraping
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s-pod-scraping
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
---
# https://github.com/kubernetes/ingress-nginx/tree/main/deploy/prometheus
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-ingress-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
      - ingress-nginx-external
  podMetricsEndpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
      scheme: http
      metricRelabelings:
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          action: replace
          targetLabel: __scheme__
          regex: (https?)
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          targetLabel: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - sourceLabels: [__meta_kubernetes_service_name]
          regex: prometheus-server
          action: drop
