apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: tasks
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      initContainers:
        - name: erlang-cookie-copy
          image: registry.internal.aleemhaji.com/busybox:1.35.0
          volumeMounts:
            - name: rabbitmq-erlang-cookie
              mountPath: /root/src
            - name: rabbitmq-persistent-storage
              mountPath: /root/dest
          command:
            - cp
            - /root/src/.erlang-cookie
            - /root/dest/.erlang-cookie
      containers:
        - name: rabbitmq
          image: registry.internal.aleemhaji.com/rabbitmq:3.11.15-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password
            - name: RABBITMQ_NODENAME
              value: rabbitmq
      volumes:
        - name: rabbitmq-erlang-cookie
          secret:
            secretName: rabbitmq-secrets
        - name: rabbitmq-persistent-storage
          emptyDir: {}
      #     iscsi:
      #       targetPortal: 192.168.96.4
      #       iqn: iqn.2019-05.com.aleemhaji.internal.ctl:rabbitmq
      #       lun: 61
      #       fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: tasks
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 5672
      name: rmq
      protocol: TCP
    - port: 15672
      name: management
      protocol: TCP
  selector:
    app: rabbitmq
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management-ingress-redirect
  namespace: tasks
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://rabbitmq-management.internal.aleemhaji.com
spec:
  rules:
    - host: rabbitmq-management
    - host: rabbitmq-management.home
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management-ingress
  namespace: tasks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - rabbitmq-management.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: rabbitmq-management.internal.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
