apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-http-bridge-server
  namespace: tasks
  labels:
    app: rmq-http-bridge
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: rmq-http-bridge-server
  template:
    metadata:
      labels:
        app: rmq-http-bridge-server
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: rmq-http-bridge-server
          image: registry.internal.aleemhaji.com/rmq-http-bridge:v0.0.6
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          env:
            - name: RABBITMQ_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: connection_string
            - name: RABBITMQ_MANAGEMENT_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: management_connection_string
          args:
            - server
            - --queue
            - tasks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-http-bridge-worker
  namespace: tasks
  labels:
    app: rmq-http-bridge
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: rmq-http-bridge-worker
  template:
    metadata:
      labels:
        app: rmq-http-bridge-worker
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: rmq-http-bridge-worker
          image: registry.internal.aleemhaji.com/rmq-http-bridge:v0.0.6
          env:
            - name: RABBITMQ_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: connection_string
          args:
            - worker
            - --queue
            - tasks
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: rmq-http-bridge
  namespace: tasks
  labels:
    app: rmq-http-bridge
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: rmq-http-bridge-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rmq-http-bridge-ingress
  namespace: tasks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - tasks.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: tasks.internal.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rmq-http-bridge
                port:
                  number: 8080
