apiVersion: v1
kind: ServiceAccount
metadata:
  name: rmq-bridge-autoscaler
  namespace: tasks
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rmq-bridge-autoscaler
  namespace: tasks
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rmq-bridge-autoscaler
  namespace: tasks
subjects:
  - kind: ServiceAccount
    name: rmq-bridge-autoscaler
roleRef:
  kind: Role
  name: rmq-bridge-autoscaler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-http-bridge-autoscaler
  namespace: tasks
  labels:
    app: rmq-http-bridge
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: rmq-http-bridge-autoscaler
  template:
    metadata:
      labels:
        app: rmq-http-bridge-autoscaler
    spec:
      serviceAccountName: rmq-bridge-autoscaler
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: rmq-http-bridge-autoscaler
          image: registry.internal.aleemhaji.com/rmq-bridge-autoscaler:latest
          command:
            - /scripts/autoscaler.sh
          volumeMounts:
            - name: script
              mountPath: /scripts
          env:
            - name: TASK_SERVER_URL
              value: https://tasks.internal.aleemhaji.com
      volumes:
        - name: script
          configMap:
            name: rmq-bridge-autoscaler-script
            defaultMode: 0755
