apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secrets
data:
  credentials.json: "${CLOUDFLARED_SECRET_BASE64}"
  cert.pem: "${CLOUDFLARED_CERT_BASE64}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: aleemhaji-com
    loglevel: debug

    metrics: 0.0.0.0:2000

    no-autoupdate: true

    ingress:
      - hostname: "readme.aleemhaji.com"
        service: http://readme.default.svc.cluster.local:80
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: cloudflared
          image: registry.internal.aleemhaji.com/cloudflare/cloudflared:2024.10.1
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          env:
            - name: TUNNEL_ORIGIN_CERT
              value: /etc/cloudflared/creds/cert.pem
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secrets
                  key: credentials.json
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: cloudflared-secrets
        - name: config
          configMap:
            name: cloudflared-config
            items:
              - key: config.yaml
                path: config.yaml
