apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: heimdall
          image: registry.internal.aleemhaji.com/heimdall:2.6.3
          ports:
            - containerPort: 80
          env:
            - name: APP_URL
              value: https://internal.aleemhaji.com
          volumeMounts:
            - name: heimdall-persistent-storage
              mountPath: /config
      volumes:
        - name: heimdall-persistent-storage
          nfs:
            server: 192.168.96.4
            path: /mnt/main/apps/heimdall
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: heimdall
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - internal.aleemhaji.com
      secretName: external-certificate-files
  rules:
    - host: internal.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heimdall
                port:
                  number: 80
