apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  labels:
    app: plex
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: plex
  serviceName: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - jellyfin
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: plex
          image: registry.internal.aleemhaji.com/pms-docker:1.40.4.8679-424562606
          ports:
            - containerPort: 32400
          env:
            - name: ALLOWED_NETWORKS
              value: 192.168.2.0/24
            - name: ADVERTISE_IP
              value: https://${LOAD_BALANCER_IP}:32400
            - name: CHANGE_CONFIG_DIR_OWNERSHIP
              value: "false"
          volumeMounts:
            - name: plex-persistent-storage
              mountPath: /config
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /identity
              port: 32400
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 120
            periodSeconds: 60
      volumes:
        - name: plex-persistent-storage
          iscsi:
            targetPortal: 192.168.96.4
            iqn: iqn.2019-05.com.aleemhaji.internal.ctl:plex
            lun: 14
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  ports:
    - port: 32400
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: ${LOAD_BALANCER_IP}
  selector:
    app: plex
