apiVersion: apps/v1
kind: Deployment
metadata:
  name: remindmebot-deployment
  labels:
    app: remindmebot
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: remindmebot
  template:
    metadata:
      name: remindmebot
      labels:
        app: remindmebot
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: remindmebot
          image: registry.internal.aleemhaji.com/remindmebot:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DEBUG
              value: "1"
            - name: BOT_NAME
              valueFrom:
                configMapKeyRef:
                  name: remindmebot-config
                  key: bot_username
            - name: BOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: remindmebot-secrets
                  key: bot_api_key
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: remindmebot-secrets
                  key: database
            - name: REMOTE_BASE_URL
              value: https://remindmebot.aleemhaji.com/
            - name: FRONT_END_URL
              value: https://remindmebot.aleemhaji.com/
---
apiVersion: v1
kind: Service
metadata:
  name: remindmebot
  labels:
    app: remindmebot
spec:
  ports:
    - port: 80
      protocol: TCP
  type: NodePort
  selector:
    app: remindmebot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: remindmebot-scheduler
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: remindmebot-scheduler
  serviceName: remindmebot-scheduler
  template:
    metadata:
      name: remindmebot-scheduler
      labels:
        app: remindmebot-scheduler
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: remindmebot-scheduler
          image: registry.internal.aleemhaji.com/curl:7.80.0
          command:
            - sh
            - -c
            - |
              while true; do \
                echo "Running scheduler... $(date -u +%Y-%m-%dT%H:%M:%SZ)"; \
                curl -X POST -fsSL http://remindmebot/schedule; \
                sleep 60; \
              done
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: remindmebot-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
spec:
  tls:
    - hosts:
        - remindmebot.aleemhaji.com
      secretName: external-certificate-files
  rules:
    - host: remindmebot.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: remindmebot
              servicePort: 80
