apiVersion: apps/v1
kind: Deployment
metadata:
  name: remindmebot-deployment
  labels:
    app: remindmebot
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: remindmebot
  template:
    metadata:
      name: remindmebot
      labels:
        app: remindmebot
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: remindmebot
          image: registry.internal.aleemhaji.com/remindmebot:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DEBUG
              value: "1"
            - name: BOT_NAME
              valueFrom:
                configMapKeyRef:
                  name: remindmebot-config
                  key: bot_username
            - name: BOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: remindmebot-secrets
                  key: bot_api_key
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: remindmebot-secrets
                  key: database
            - name: REMOTE_BASE_URL
              value: https://remindmebot.aleemhaji.com/
            - name: FRONT_END_URL
              value: https://remindmebot.aleemhaji.com/
---
apiVersion: v1
kind: Service
metadata:
  name: remindmebot
  labels:
    app: remindmebot
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: remindmebot
---
apiVersion: batch/v1
kind: Job
metadata:
  name: remindmebot-init
  labels:
    job: remindmebot-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: remindmebot-init
          image: curlimages/curl:7.72.0
          command:
            - sh
            - -c
            - |
              curl \
                  -u "${BOT_NAME}:${BOT_API_KEY}" \
                  -H "Content-Type: application/json" \
                  -X "POST" \
                  -d '{"webhook": "https://remindmebot.aleemhaji.com/receive", "features": {"receiveReadReceipts": false, "receiveIsTyping": false, "manuallySendReadReceipts": false, "receiveDeliveryReceipts": false}}' \
                  https://api.kik.com/v1/config
          env:
            - name: BOT_NAME
              valueFrom:
                configMapKeyRef:
                  name: remindmebot-config
                  key: bot_username
            - name: BOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: remindmebot-secrets
                  key: bot_api_key
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: remindmebot-scheduler
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: remindmebot-scheduler
  serviceName: remindmebot-scheduler
  template:
    metadata:
      name: remindmebot-scheduler
      labels:
        app: remindmebot-scheduler
    spec:
      containers:
        - name: remindmebot-scheduler
          image: curlimages/curl:7.72.0
          command:
            - sh
            - -c
            - |
              while true; do \
                echo "Running scheduler... $(date -u +%Y-%m-%dT%H:%M:%SZ)"; \
                curl -X POST -fsSL http://remindmebot/schedule; \
                sleep 60; \
              done
