apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-monitor
spec:
  schedule: "0 16 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            # Temporary image while I work through actually getting scripts
            #   to do what they need to.
            - name: image-monitor
              image: registry.internal.aleemhaji.com/kubectl:1.21.0
              command:
                - /scripts/image-monitor.sh
              volumeMounts:
                - name: image-monitor-scripts
                  mountPath: /scripts
          volumes:
            - name: image-monitor-scripts
              configMap:
                name: image-monitor-config
                defaultMode: 0755
