apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-deployment
  labels:
    app: guacamole
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      name: guacamole
      labels:
        app: guacamole
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: guacd
          image: registry.internal.aleemhaji.com/guacd:1.2.0
        - name: guacamole
          image: registry.internal.aleemhaji.com/guacamole:1.2.0
          ports: 
            - containerPort: 8080
          env:
            - name: GUACD_HOSTNAME
              value: localhost
            - name: MYSQL_HOSTNAME
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: guacamole-config
                  key: mysql_database
            - name: MYSQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: guacamole-secrets
                  key: mysql_password
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: guacamole-config
                  key: mysql_user
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  labels:
    app: guacamole
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: guacamole
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guacamole-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://guacamole.internal.aleemhaji.com
spec:
  rules:
    - host: guacamole
    - host: guacamole.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guacamole-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /guacamole/$1
spec:
  tls:
    - hosts:
        - guacamole.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: guacamole.internal.aleemhaji.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: guacamole
              servicePort: 8080
