apiVersion: batch/v1
kind: Job
metadata:
  name: guacamole-app-init
  labels:
    job: guacamole-app-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      initContainers:
        - name: guacamole-app-init-script-creator
          image: registry.internal.aleemhaji.com/guacamole:1.3.0
          command:
            - sh
            - -c
            - /opt/guacamole/bin/initdb.sh --mysql > /scripts/init.sql
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
      containers:
        - name: guacamole-app-init
          image: registry.internal.aleemhaji.com/mysql:8.0.23
          command:
            - sh
            - -cex
            - |
              # The Guacamole init job isn't idempotent, so check for the
              #   presence of the first table it errors out on and exit if it
              #   already exists.
              if mysql -h ${MYSQL_HOST} -u root ${GUACAMOLE_DB_NAME} -e 'select 1 from guacamole_connection_group'; then
                echo >&2 "Guacamole MySQL database has probably already been initialized."
                exit 0
              fi
              mysql -h ${MYSQL_HOST} -u root ${GUACAMOLE_DB_NAME} < /scripts/init.sql
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root_password
            - name: MYSQL_HOST
              value: mysql
            - name: GUACAMOLE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: guacamole-config
                  key: mysql_database
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
      volumes:
        - name: init-scripts
          emptyDir: {}
