apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstack-notifier
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookstack-notifier-shell-monitor
subjects:
  - kind: ServiceAccount
    name: bookstack-notifier
roleRef:
  kind: Role
  name: shell-monitor
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: bookstack-notifier-script
binaryData:
  script.sh: ${BOOKSTACK_NOTIFIER_SCRIPT}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack-notifier-deployment
  labels:
    app: bookstack-notifier
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-notifier
  template:
    metadata:
      labels:
        app: bookstack-notifier
    spec:
      serviceAccountName: bookstack-notifier
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: bookstack-notifier
          image: registry.internal.aleemhaji.com/kubectl:1.21.0
          command:
            - /scripts/base/script.sh
          env:
            - name: CONFIG_MAP_NAME
              value: bookstack-notifier-monitor
            - name: UPDATE_SCRIPT
              value: /scripts/monitor/script.sh
            - name: UPDATE_INTERVAL
              value: "3600"
            - name: TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: bookstack-notifier-secrets
                  key: token_id
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: bookstack-notifier-secrets
                  key: token_secret
          volumeMounts:
            - name: shell-monitor-base-scripts
              mountPath: /scripts/base
            - name: bookstack-notifier-script
              mountPath: /scripts/monitor
      volumes:
        - name: shell-monitor-base-scripts
          configMap:
            name: shell-monitor-base-config
            defaultMode: 0755
        - name: bookstack-notifier-script
          configMap:
            name: bookstack-notifier-script
            defaultMode: 0755
