apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: gitea
          image: registry.internal.aleemhaji.com/gitea:1.22.1-rootless
          ports:
            - containerPort: 3000
            - containerPort: 2222
          volumeMounts:
            - name: gitea-persistent-storage
              mountPath: /data
            - name: ssl-cert
              mountPath: /etc/ssl/certs/
          env:
            - name: GITEA__OAUTH2__JWT_SIGNING_ALGORITHM
              value: HS256
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
      volumes:
        - name: gitea-persistent-storage
          nfs:
            server: 192.168.96.4
            path: /mnt/main/apps/gitea
        - name: ssl-cert
          projected:
            sources:
              - secret:
                  name: internal-certificate-files
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  type: LoadBalancer
  loadBalancerIP: ${LOAD_BALANCER_IP}
  ports:
    - port: 443
      protocol: TCP
      name: web
      targetPort: 3000
    - port: 22
      protocol: TCP
      name: ssh
      targetPort: 2222
  selector:
    app: gitea
