apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-monitor
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: events-monitor
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: events-monitor-shell-monitor
subjects:
- kind: ServiceAccount
  name: events-monitor
roleRef:
  kind: Role
  name: shell-monitor
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: events-monitor-events-monitor
subjects:
- kind: ServiceAccount
  name: events-monitor
  namespace: default
roleRef:
  kind: ClusterRole
  name: events-monitor
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: event-monitor-script
  labels:
    app: events-shell-monitor
data:
  script.sh: |
    event_template='{{range .items}}{{.metadata.creationTimestamp}} ({{.count}}) {{.source.host}}/{{.involvedObject.namespace}}/{{.involvedObject.name}}
      {{.message}}
    {{end}}'

    kubectl get events --sort-by='.metadata.creationTimestamp' --field-selector "type!=Normal" -A -o "template=$event_template"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-shell-monitor-deployment
  labels:
    app: events-shell-monitor
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: events-shell-monitor
  template:
    metadata:
      labels:
        app: events-shell-monitor
    spec:
      serviceAccountName: events-monitor
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: shell-monitor
          image: registry.internal.aleemhaji.com/kubectl:1.21.0
          command:
             - /scripts/base/script.sh
          env:
            - name: CONFIG_MAP_NAME
              value: recent-events-monitor
            - name: UPDATE_SCRIPT
              value: /scripts/monitor/script.sh
            - name: UPDATE_INTERVAL
              value: "3600"
          volumeMounts:
            - name: shell-monitor-base-scripts
              mountPath: /scripts/base
            - name: event-monitor-script
              mountPath: /scripts/monitor
      volumes:
        - name: shell-monitor-base-scripts
          configMap:
            name: shell-monitor-base-config
            defaultMode: 0755
        - name: event-monitor-script
          configMap:
            name: event-monitor-script
            defaultMode: 0755
