apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-monitor
  namespace: ${SHELL_MONITOR_NAMESPACE}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shell-monitor
  namespace: ${SHELL_MONITOR_NAMESPACE}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shell-monitor
  namespace: ${SHELL_MONITOR_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: shell-monitor
roleRef:
  kind: Role
  name: shell-monitor
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: shell-monitor-base-config
  namespace: ${SHELL_MONITOR_NAMESPACE}
  labels:
    app: shell-monitor-base-script
binaryData:
  script.sh: "${SHELL_MONITOR_SCRIPT}"
