apiVersion: apps/v1
kind: Deployment
metadata:
  name: diun-deployment
  labels:
    app: diun
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: diun
          image: registry.internal.aleemhaji.com/diun:4.21.0
          command:
            - sh
            - -eufc
            - |
              while [ ! -f /config/diun.yaml ]; do echo >&2 "Waiting for diun.yaml..."; sleep 60; done && \
              diun serve
          env:
            - name: TZ
              value: "America/Toronto"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_JSON
              value: "false"
            - name: DIUN_WATCH_WORKERS
              value: "20"
            - name: DIUN_WATCH_SCHEDULE
              value: "0 22 * * *"
            - name: DIUN_NOTIF_SLACK_WEBHOOKURL
              valueFrom:
                secretKeyRef:
                  name: diun-secrets
                  key: webhook_url
            - name: DIUN_PROVIDERS_FILE_FILENAME
              value: /config/diun.yaml
            - name: DIUN_DB_PATH
              value: /config/diun.db
            - name: DIUN_WATCH_FIRSTCHECKNOTIF
              value: "true"
          volumeMounts:
            - name: config-dir
              mountPath: /config
        - name: diun-config-generator
          image: registry.internal.aleemhaji.com/kubectl:1.21.0
          command:
            - sh
            - -eufc
            - |
              while true; do
                curl -fsS  https://raw.githubusercontent.com/Eagerod/home-network/master/hope.yaml |\
                  /scripts/diun-yaml-generator.sh > /config/diun.yaml;
                sleep 3600;
              done;
          volumeMounts:
            - name: config-dir
              mountPath: /config
            - name: scripts-dir
              mountPath: /scripts
      volumes:
        - name: config-dir
          emptyDir: {}
        - name: scripts-dir
          configMap:
            name: diun-scripts
            defaultMode: 0755