apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium-deployment
  labels:
    app: trilium
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: trilium
          image: registry.internal.aleemhaji.com/trilium:0.46.7
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trilium-persistent-storage
              mountPath: /home/node/trilium-data
      volumes:
        - name: trilium-persistent-storage
          nfs:
            server: 192.168.96.4
            path: /mnt/main/apps/trilium
---
apiVersion: v1
kind: Service
metadata:
  name: trilium
  labels:
    app: trilium
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: trilium
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trilium-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://trilium.internal.aleemhaji.com
spec:
  rules:
    - host: trilium
    - host: trilium.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trilium-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - trilium.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: trilium.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: trilium
              servicePort: 8080
