#!/usr/bin/env bash
#
# mr is an application designed to easily support building out a multi-reddit
#   tracker using the blob service at https://aleem.haji.ca/blob
__blob_file_get() {
	if [ $# -ne 1 ]; then
		exit -1
	fi
	BLOBSTORE_READ_ACL=$DEFAULT_BLOBSTORE_READ_ACL blob cp $1
}

__blob_file_append() {
	if [ $# -ne 2 ]; then
		exit -1
	fi
	BLOBSTORE_READ_ACL=$DEFAULT_BLOBSTORE_READ_ACL \
	BLOBSTORE_WRITE_ACL=$DEFAULT_BLOBSTORE_WRITE_ACL \
	blob append $1 -s $2
}

if [ $# -lt 1 ]; then
	echo "Must provide a command in (link save add links)"
	exit -1
fi

if [ $1 == 'link' ]; then
	echo "https://reddit.com/r/"$(__blob_file_get $MULTI_REDDIT_SUBS_LOCATION | sed 's/\\n/\n/g' | grep -v '^$' | tr '\n' '+' | sed 's/+$//g')

	echo ""
elif [ $1 == 'add' ]; then
	if [ $# -ne 2 ]; then
		echo "Must provide a subreddit name to add"
		exit -1
	fi
	__blob_file_append $MULTI_REDDIT_SUBS_LOCATION "$2\n"
elif [ $1 == 'links' ]; then
	__blob_file_get $MULTI_REDDIT_SAVED_LOCATION | sed 's/\\n/\n/g'
elif [ $1 == 'save' ]; then
	if [ $# -ne 2 ]; then
		echo "Must provide a url to save"
		exit -1
	fi
	__blob_file_append $MULTI_REDDIT_SAVED_LOCATION "$2\n"
else
	echo "Must provide a command in (link save add links)"
	exit -1
fi

