apiVersion: batch/v1
kind: Job
metadata:
  generateName: rotate-node-${ROTATE_NODE_NAME}-manual-
  namespace: dev
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: rotate-node-manual
    spec:
      nodeSelector:
        aleemhaji.com/oldest: "false"
      restartPolicy: Never
      serviceAccountName: rotate-node
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - ${ROTATE_NODE_NAME}
      # This process uses ssh-copy-id, which requires that the SSH dir on
      #   the host be writable.
      # Mounting a secret directly as a mount leads to a read-only fs, so
      #   contents have be copied beforehand.
      initContainers:
        - name: rotate-node-ssh-copy
          image: registry.internal.aleemhaji.com/busybox:1.37.0
          volumeMounts:
            - name: ssh-key-temp
              mountPath: /root/.ssh-temp
            - name: writable-ssh-dir
              mountPath: /root/.ssh
          command:
            - sh
            - -c
            - |
              cp -R /root/.ssh-temp/. /root/.ssh/
      containers:
        - name: rotate-node
          image: registry.internal.aleemhaji.com/home-network:latest
          imagePullPolicy: Always
          command:
            - /src/node-rotator/rotate-node.sh
            - ${ROTATE_NODE_NAME}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SLACK_BOT_ALERTING_CHANNEL
              value: ${SLACK_BOT_ALERTING_CHANNEL}
            - name: LOAD_BALANCER_IP
              value: ignored-but-necessary
            - name: VM_IMAGE_NAME
              value: ${VM_IMAGE_NAME}
            - name: ESXI_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rotate-node-secrets
                  key: esxi_root_password
            - name: VM_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rotate-node-secrets
                  key: vm_root_password
            - name: VM_MANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rotate-node-secrets
                  key: vm_management_password
          volumeMounts:
            - name: packer-data
              mountPath: /var/lib/packer
            - name: writable-ssh-dir
              mountPath: /root/.ssh
      volumes:
        - name: packer-data
          nfs:
            server: 192.168.96.4
            path: /mnt/main/apps/packer
        - name: ssh-key-temp
          secret:
            secretName: dev-ssh-key
            defaultMode: 0600
        - name: writable-ssh-dir
          emptyDir: {}
