apiVersion: v1
kind: ServiceAccount
metadata:
  name: rotate-node-tagger
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rotate-node-tagger
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rotate-node-tagger
subjects:
  - kind: ServiceAccount
    name: rotate-node-tagger
    namespace: dev
roleRef:
  kind: ClusterRole
  name: rotate-node-tagger
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rotate-node-tagger-script
  namespace: dev
  labels:
    app: rotate-node-tagger
binaryData:
  script.sh: ${ROTATE_NODE_TAGGER_SCRIPT}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rotate-node-tagger
  namespace: dev
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rotate-node-tagger
        spec:
          restartPolicy: OnFailure
          serviceAccountName: rotate-node-tagger
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: rotate-node
              image: registry.internal.aleemhaji.com/kubectl:1.21.0
              command:
                - /scripts/script.sh
              volumeMounts:
                - name: rotate-node-tagger-scripts
                  mountPath: /scripts
          volumes:
            - name: rotate-node-tagger-scripts
              configMap:
                name: rotate-node-tagger-script
                defaultMode: 0755
