apiVersion: v1
kind: ServiceAccount
metadata:
  name: rotate-node
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rotate-node
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "delete"]
apiVersion: rbac.authorization.k8s.io/v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rotate-node
subjects:
  - kind: ServiceAccount
    name: rotate-node
    namespace: dev
roleRef:
  kind: ClusterRole
  name: rotate-node
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rotate-node
  namespace: dev
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: rotate-node
        spec:
          nodeSelector:
            aleemhaji.com/oldest: "false"
          restartPolicy: Never
          serviceAccountName: rotate-node
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: rotate-node
              image: registry.internal.aleemhaji.com/home-network:latest
              command: 
                - bash
                - -eufo
                - pipefail
                - -c
                - |
                  SLACK_URL="https://slackbot.internal.aleemhaji.com/message"

                  slack() {
                      curl -sS -X POST -H "X-SLACK-CHANNEL-ID: ${SLACK_BOT_ALERTING_CHANNEL}" -d "$@" "$SLACK_URL"
                  }

                  cd /src
                  source .env.new
                  node_id="$(kubectl get nodes -l "aleemhaji.com/oldest=true" -o template="{{range .items}}{{.metadata.name}}{{end}}")"

                  if [ -z "$node_id" ]; then
                    slack "Failed to find oldest node in cluster."
                    exit 1
                  fi

                  # There's a label selector to prevent this, but just in case
                  #   that ever changes.
                  if [ "$node_id" = "$NODE_NAME" ]; then
                    slack "Node rotator wants to kill itself. Failing early."
                    exit 1
                  fi

                  if hope --config hope.yaml kubectl get node $node_id 2> /dev/null; then
                    slack "Node rotator running on $NODE_NAME removing node from cluster ($node_id)"
                    echo hope --config hope.yaml node reset --force --delete-local-data $node_id
                  fi

                  echo hope --config hope.yaml vm stop $node_id
                  echo hope --config hope.yaml vm delete $node_id
                  echo hope --config hope.yaml vm create $node_id
                  echo hope --config hope.yaml vm start $node_id
                  echo hope --config hope.yaml vm ip $node_id
                  echo sshpass -p "$VM_MANAGEMENT_PASSWORD" hope --config hope.yaml node ssh $node_id
                  echo hope --config hope.yaml node hostname $node_id $node_id
                  echo hope --config hope.yaml node init --force $node_id
              ports:
                - containerPort: 8067
                  protocol: TCP
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: packer-data
                  mountPath: /var/lib/packer
                - name: ssh-key
                  mountPath: /root/.ssh
          volumes:
            - name: packer-data
              nfs:
                server: 192.168.96.4
                path: /mnt/main/apps/packer
            - name: ssh-key
              secret:
                secretName: dev-ssh-key
                defaultMode: 0600