apiVersion: v1
kind: ServiceAccount
metadata:
  name: rotate-node
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rotate-node
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "delete"]
apiVersion: rbac.authorization.k8s.io/v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rotate-node
subjects:
  - kind: ServiceAccount
    name: rotate-node
    namespace: dev
roleRef:
  kind: ClusterRole
  name: rotate-node
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rotate-node-script
  namespace: dev
  labels:
    app: rotate-node
binaryData:
  script.sh: ${ROTATE_NODE_SCRIPT}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rotate-node
  namespace: dev
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: rotate-node
        spec:
          nodeSelector:
            aleemhaji.com/oldest: "false"
          restartPolicy: Never
          serviceAccountName: rotate-node
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: rotate-node
              image: registry.internal.aleemhaji.com/home-network:latest
              command:
                - /scripts/script.sh
              ports:
                - containerPort: 8067
                  protocol: TCP
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: packer-data
                  mountPath: /var/lib/packer
                - name: ssh-key
                  mountPath: /root/.ssh
                - name: rotate-node-scripts
                  mountPath: /scripts
          volumes:
            - name: packer-data
              nfs:
                server: 192.168.96.4
                path: /mnt/main/apps/packer
            - name: ssh-key
              secret:
                secretName: dev-ssh-key
                defaultMode: 0600
            - name: rotate-node-scripts
              configMap:
                name: rotate-node-script
                defaultMode: 0755
