apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-internal-deployment
  labels:
    app: nginx-internal
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: nginx-internal
  template:
    metadata:
      name: nginx-internal
      labels:
        app: nginx-internal
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.12
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-servers
              mountPath: /etc/nginx/conf.d/
            - name: internal-certs
              mountPath: /etc/ssl/certs/internal
            - name: external-certs
              mountPath: /etc/ssl/certs/external
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-servers
          configMap:
            name: nginx-servers-internal
        - name: internal-certs
          projected:
            sources:
              - secret:
                  name: internal-certificate-files
        - name: external-certs
          projected:
            sources:
              - secret:
                  name: external-certificate-files
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal
  labels:
    app: nginx-internal
spec:
  ports:
    - port: 80
      protocol: TCP
      name: nginx-http-port
    - port: 443
      protocol: TCP
      name: nginx-https-port
  type: LoadBalancer
  loadBalancerIP:
  selector:
    app: nginx-internal
