apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: firefly-iii
  template:
    metadata:
      labels:
        app: firefly-iii
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: firefly-iii
          image: registry.internal.aleemhaji.com/fireflyiii-core:version-6.2.10
          ports:
            - containerPort: 8080
          env:
            - name: TRUSTED_PROXIES
              value: '**'
            - name: APP_URL
              value: https://firefly.internal.aleemhaji.com
            - name: APP_ENV
              value: local
            - name: DB_HOST
              value: mysql
            - name: DB_CONNECTION
              value: mysql
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: firefly-config
                  key: mysql_user
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: firefly-config
                  key: mysql_database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: mysql_password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: app_key
            - name: USE_ENCRYPTION
              value: "false"
            - name: MAIL_MAILER
              value: log
          volumeMounts:
            - name: file-uploads
              mountPath: /var/www/firefly-iii/storage/upload
      volumes:
        - name: file-uploads
          nfs:
            server: 192.168.96.4
            path: /mnt/main/apps/firefly-iii
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: firefly-iii
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-iii-redirect
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://firefly.internal.aleemhaji.com
spec:
  ingressClassName: nginx
  rules:
    - host: firefly
    - host: firefly.home
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-iii
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - firefly.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: firefly.internal.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: firefly-iii
                port:
                  number: 8080
