apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-data-importer-deployment
  labels:
    app: firefly-iii-data-importer
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: firefly-iii-data-importer
  template:
    metadata:
      labels:
        app: firefly-iii-data-importer
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: firefly-iii-data-importer
          image: registry.internal.aleemhaji.com/firefly-iii-importer:0.8.0
          ports:
            - containerPort: 8080
          env:
            - name: TRUSTED_PROXIES
              value: '**'
            - name: FIREFLY_III_URL
              value: https://firefly.internal.aleemhaji.com
            - name: VANITY_URL
              value: https://firefly.internal.aleemhaji.com
            # - name: FIREFLY_III_CLIENT_ID
            #   value: "164"
            - name: FIREFLY_III_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: importer_pat
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-data-importer
  labels:
    app: firefly-data-importer
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: firefly-iii-data-importer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: firefly-data-importer-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://firefly-data-importer.internal.aleemhaji.com
spec:
  rules:
    - host: firefly-data-importer
    - host: firefly-data-importer.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: firefly-data-importer-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  tls:
    - hosts:
        - firefly-data-importer.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: firefly-data-importer.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: firefly-data-importer
              servicePort: 8080
