apiVersion: batch/v1
kind: Job
metadata:
  name: firefly-app-init
  labels:
    job: firefly-app-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: firefly-app-init
          image: registry.internal.aleemhaji.com/fireflyiii-core:version-5.7.15
          command:
            - sh
            - -c
            - |
              php artisan migrate && \
              php artisan firefly:upgrade-database && \
              php artisan passport:install
          # https://github.com/firefly-iii/firefly-iii/blob/4.7.5.3/.env.docker#L25
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: firefly-config
                  key: mysql_user
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: firefly-config
                  key: mysql_database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: mysql_password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: app_key
