# Simple shell script to kill pods that have been restarted more than a
#   specified number of times.
# May be able to help recover pods that have been allocated to a node that's
#   started seeing some condition that makes it fail, like an NFS share that
#   needs to be remounted.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-killer
  namespace: ${POD_KILLER_NAMESPACE}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-killer
  namespace: ${POD_KILLER_NAMESPACE}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-killer
  namespace: ${POD_KILLER_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: pod-killer
roleRef:
  kind: Role
  name: pod-killer
  apiGroup: rbac.authorization.k8s.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: pod-killer
  name: pod-killer-config
  namespace: ${POD_KILLER_NAMESPACE}
binaryData:
  script.sh: ${POD_KILLER_SCRIPT}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-killer-deployment
  namespace: ${POD_KILLER_NAMESPACE}
  labels:
    app: pod-killer
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: pod-killer
  template:
    metadata:
      labels:
        app: pod-killer
    spec:
      serviceAccountName: pod-killer
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: pod-killer
          image: registry.internal.aleemhaji.com/kubectl:1.21.0
          command:
            - /scripts/script.sh
            - "10"
          volumeMounts:
            - name: pod-killer-scripts
              mountPath: /scripts
      volumes:
        - name: pod-killer-scripts
          configMap:
            name: pod-killer-config
            defaultMode: 0755
