apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: mysql
          image: registry.internal.aleemhaji.com/mysql:5.7.43
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-certs
              mountPath: /etc/ssl
          args:
            - --ssl-cert=/etc/ssl/tls.crt
            - --ssl-key=/etc/ssl/tls.rsa.key
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root_password
      volumes:
        - name: mysql-certs
          projected:
            sources:
              - secret:
                  name: internal-certificate-files
        - name: mysql-persistent-storage
          iscsi:
            targetPortal: 192.168.96.4
            iqn: iqn.2019-05.com.aleemhaji.internal.ctl:mysql
            lun: 12
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: registry.internal.aleemhaji.com
          containers:
            - name: mysql-backup
              image: registry.internal.aleemhaji.com/mysql:5.7.37
              command:
                - sh
                - /scripts/mysql-backup.sh
              volumeMounts:
                - name: backups
                  mountPath: /var/lib/backups
                - name: backup-script
                  mountPath: /scripts
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secrets
                      key: root_password
                - name: MYSQL_HOST
                  value: mysql
          volumes:
            - name: backups
              nfs:
                server: 192.168.96.4
                path: /mnt/main/backup/apps/mysql
            - name: backup-script
              projected:
                sources:
                  - configMap:
                      name: mysql-backup
          restartPolicy: OnFailure
