apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: mysql:5.7.26
              command:
                - sh
                - /scripts/mysql-backup.sh
              volumeMounts:
              - name: backups
                mountPath: /var/lib/backups
              - name: backup-script
                mountPath: /scripts
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-root-password
                      key: value
                - name: MYSQL_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: network-ip-assignments
                      key: mysql
          volumes:
            - name: backups
              nfs:
                server: 192.168.96.4
                path: /mnt/main/backup/mysql
            - name: backup-script
              projected:
                sources:
                  - configMap:
                      name: mysql-backup
          restartPolicy: OnFailure
