apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: mysql
          image: mysql:5.7.26
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-certs
              mountPath: /etc/ssl
          args:
            - --ssl-cert=/etc/ssl/tls.crt
            - --ssl-key=/etc/ssl/tls.rsa.key
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: value
      volumes:
        - name: mysql-certs
          projected:
            sources:
              - secret:
                  name: internal-certificate-files
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
  type: NodePort
  selector:
    app: mysql
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: mysql:5.7.26
              command:
                - sh
                - /scripts/mysql-backup.sh
              volumeMounts:
              - name: backups
                mountPath: /var/lib/backups
              - name: backup-script
                mountPath: /scripts
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-root-password
                      key: value
                - name: MYSQL_HOST
                  value: mysql
          volumes:
            - name: backups
              nfs:
                server: 192.168.96.4
                path: /mnt/main/backup/mysql
            - name: backup-script
              projected:
                sources:
                  - configMap:
                      name: mysql-backup
          restartPolicy: OnFailure
