apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unifi-controller
  labels:
    app: unifi
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  serviceName: unifi-tcp
  template:
    metadata:
      labels:
        app: unifi
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: unifi
          image: registry.internal.aleemhaji.com/unifi-controller:7.4.162-custom
          ports:
            - containerPort: 8443
              protocol: TCP
              name: unifi-gui-port
            - containerPort: 8080
              protocol: TCP
              name: unspecified
            - containerPort: 8081
              protocol: TCP
              name: unifi-comms
            - containerPort: 8880
              protocol: TCP
              name: unifi-http
            - containerPort: 8843
              protocol: TCP
              name: unifi-https
            - containerPort: 6789
              protocol: TCP
              name: unifi-test-port
            - containerPort: 3478
              protocol: UDP
              name: unifi-stun-port
            - containerPort: 10001
              protocol: UDP
              name: unifi-discovery
          resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "200m"
          env:
            - name: UNIFI_SERVICE_IP
              value: ${LOAD_BALANCER_IP}
        - name: mongo
          image: registry.internal.aleemhaji.com/mongo:3.6
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "100m"
      volumes:
        - name: mongodb
          iscsi:
            targetPortal: 192.168.96.4
            iqn: iqn.2019-05.com.aleemhaji.internal.ctl:unifi-mongodb
            lun: 51
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp
  labels:
    app: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
spec:
  # https://help.ubnt.com/hc/en-us/articles/218506997
  ports:
    - port: 8443
      protocol: TCP
      name: unifi-gui-port
    - port: 8080
      protocol: TCP
      name: unifi-comms-port
    - port: 8081
      protocol: TCP
      name: unifi-unspecified-port
    - port: 8880
      protocol: TCP
      name: unifi-http-portal-port
    - port: 8843
      protocol: TCP
      name: unifi-https-portal-port
    - port: 6789
      protocol: TCP
      name: unifi-test-port
  type: LoadBalancer
  loadBalancerIP: ${LOAD_BALANCER_IP}
  selector:
    app: unifi
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-udp
  labels:
    app: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
spec:
  # https://help.ubnt.com/hc/en-us/articles/218506997
  ports:
    - port: 3478
      protocol: UDP
      name: unifi-stun-port
    - port: 10001
      protocol: UDP
      name: unifi-discovery-port
  type: LoadBalancer
  loadBalancerIP: ${LOAD_BALANCER_IP}
  selector:
    app: unifi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-redirect
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://unifi.internal.aleemhaji.com
spec:
  ingressClassName: nginx
  rules:
    - host: unifi
    - host: unifi.home
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - unifi.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: unifi.internal.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi-tcp
                port:
                  number: 8443
