apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-transmission-deployment
  labels:
    app: osstransmission
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: osstransmission
  template:
    metadata:
      labels:
        app: osstransmission
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: transmission
          image: registry.internal.aleemhaji.com/transmission:2004
          ports:
            - containerPort: 9091
            - containerPort: 51413
          env:
            - name: PEER_PORT
              value: "51413"
          volumeMounts:
            - name: downloads-persistent-storage
              mountPath: /var/lib/downloads
            - name: transmission-persistent-storage
              mountPath: /var/lib/transmission-daemon
      volumes:
        - name: downloads-persistent-storage
          nfs:
            server: 192.168.96.4
            path: /mnt/main/oss-downloads
        - name: transmission-persistent-storage
          nfs:
            server: 192.168.96.4
            path: /mnt/main/apps/oss-transmission
---
apiVersion: v1
kind: Service
metadata:
  name: osstransmission
  labels:
    app: osstransmission
spec:
  ports:
    - port: 9091
      protocol: TCP
      name: web
    - port: 51413
      protocol: TCP
      name: torrent
  selector:
    app: osstransmission
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osstransmission-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://osstransmission.internal.aleemhaji.com
spec:
  rules:
    - host: osstransmission
    - host: osstransmission.home
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osstransmission-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - osstransmission.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: osstransmission.internal.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osstransmission
                port:
                  number: 9091
