metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 2

compression_level = 2

rpc_bind_addr = "0.0.0.0:3901"
rpc_secret_file = "/etc/garage-secret"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"
root_domain = "garage-api.internal.aleemhaji.com"

[s3_web]
bind_addr = "0.0.0.0:3902"
root_domain = "garage-web.internal.aleemhaji.com"
index = "index.html"
