metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 2

compression_level = 2

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "192.168.1.244:3901"
rpc_secret = "ddeb8f2e1246c2715b22c57e83b2ab76ca02bd8e092fa913b3034fb5b6d85b17"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"
root_domain = "garage-api.internal.aleemhaji.com"

[s3_web]
bind_addr = "0.0.0.0:3902"
root_domain = "garage-web.internal.aleemhaji.com"
index = "index.html"