apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      initContainers:
        # Certificates need to have specific permissions for Postgres to accept
        #   them, so set those in a temporary volume.
        - name: cert-permissions
          image: registry.internal.aleemhaji.com/postgres:9
          command:
            - sh
            - -c
            - |
              cp /src/* /dst/
              chown postgres:postgres /dst/*
              chmod 600 /dst/*
          volumeMounts:
            - name: postgres-certs-source
              mountPath: /src
            - name: postgres-certs
              mountPath: /dst
      containers:
        - name: postgres
          image: registry.internal.aleemhaji.com/postgres:9
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /usr/local/pgsql
            - name: postgres-certs
              mountPath: /etc/ssl
          args:
            - --ssl=on
            - --ssl_cert_file=/etc/ssl/tls.crt
            - --ssl_key_file=/etc/ssl/tls.rsa.key
          env:
            - name: PGDATA
              value: /usr/local/pgsql/data
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: root_password
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: postgres-certs
          emptyDir: {}
        - name: postgres-certs-source
          projected:
            sources:
              - secret:
                  name: internal-certificate-files
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  type: NodePort
  selector:
    app: postgres
