apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobstore
  labels:
    app: blobstore
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: blobstore
  template:
    metadata:
      name: blobstore
      labels:
        app: blobstore
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: blobstore
          image: registry.internal.aleemhaji.com/blobstore:0.1.3
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"
          env:
            - name: PORT
              value: "80"
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: blobstore-secrets
                  key: database
---
apiVersion: v1
kind: Service
metadata:
  name: blobstore
  labels:
    app: blobstore
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: blobstore
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blobstore-redirect
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://blob.internal.aleemhaji.com
spec:
  ingressClassName: nginx
  rules:
    - host: blob
    - host: blob.home
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blobstore
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16M"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - blob.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: blob.internal.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blobstore
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blobstore-external
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16M"
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
        - blob.aleemhaji.com
      secretName: external-certificate-files
  rules:
    - host: blob.aleemhaji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blobstore
                port:
                  number: 80
