apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobstore-deployment
  labels:
    app: blobstore
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: blobstore
  template:
    metadata:
      name: blobstore
      labels:
        app: blobstore
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      containers:
        - name: blobstore
          image: registry.internal.aleemhaji.com/blobstore:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: blobstore-secrets
                  key: database
---
apiVersion: v1
kind: Service
metadata:
  name: blobstore
  labels:
    app: blobstore
spec:
  ports:
    - port: 80
      protocol: TCP
  type: NodePort
  selector:
    app: blobstore
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blobstore-ingress-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/temporal-redirect: https://blob.internal.aleemhaji.com
spec:
  rules:
    - host: blob
    - host: blob.home
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blobstore-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "16M"
spec:
  tls:
    - hosts:
        - blob.internal.aleemhaji.com
      secretName: internal-certificate-files
  rules:
    - host: blob.internal.aleemhaji.com
      http:
        paths:
          - path: /
            backend:
              serviceName: blobstore
              servicePort: 80
