apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      imagePullSecrets:
        - name: registry.internal.aleemhaji.com
      initContainers:
        - name: redis-init
          image: registry.internal.aleemhaji.com/busybox:1.33.1
          command:
            - sh
            - -c
            - |
              set -ex
              ord=$(hostname | sed s/redis-//)
              if [ $ord -ne 0 ]; then
                echo "slaveof redis-0.redis 6379" >> /config/redis.conf
              else
                echo "cluster-enabled yes" >> /config/redis.conf
              fi
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: redis
          image: registry.internal.aleemhaji.com/redis:5
          ports:
            - containerPort: 6379
          args:
            - /config/redis.conf
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
  type: NodePort
  selector:
    app: redis
