name: Build Test Image

on:
  push:

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build
        run: |
          docker build . -f Dockerfile.ci
